name: CICD pipeline 

on: 
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main 
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: insatll docker compose 
        run: |
           sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose version  # Verify installation
      - name:  build docker image
        run: docker build -t django-notes-app:latest .
        
      - name: login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
           echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - name: Tag and push the image to docker hub 
        run: |
          docker tag django-notes-app $DOCKER_USER/django-notes-app:latest
          docker push $DOCKER_USER/django-notes-app:latest
      - name: deploy the application
        run: |
           docker-compose down
           docker-compose up -d
       
        
